// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRE2Y_gJrBQAl6l3457FuAfmK3tw9jht4',
    appId: '1:362446433212:web:62736a4dcb52c7fc7c19b9',
    messagingSenderId: '362446433212',
    projectId: 'flutter-test-217c8',
    authDomain: 'flutter-test-217c8.firebaseapp.com',
    storageBucket: 'flutter-test-217c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5roqOzZa21SnDOw-VL3SKouO7_ZBxHXk',
    appId: '1:362446433212:android:b707ef17738f5cf77c19b9',
    messagingSenderId: '362446433212',
    projectId: 'flutter-test-217c8',
    storageBucket: 'flutter-test-217c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCArIu0-a3snMou7oycPz1l2A8zEg5R7w',
    appId: '1:362446433212:ios:fd742d6cf0aa2cd97c19b9',
    messagingSenderId: '362446433212',
    projectId: 'flutter-test-217c8',
    storageBucket: 'flutter-test-217c8.firebasestorage.app',
    iosBundleId: 'com.jimin.flutterprac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCArIu0-a3snMou7oycPz1l2A8zEg5R7w',
    appId: '1:362446433212:ios:ba118f541c9af38c7c19b9',
    messagingSenderId: '362446433212',
    projectId: 'flutter-test-217c8',
    storageBucket: 'flutter-test-217c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRE2Y_gJrBQAl6l3457FuAfmK3tw9jht4',
    appId: '1:362446433212:web:89f4e90d719172917c19b9',
    messagingSenderId: '362446433212',
    projectId: 'flutter-test-217c8',
    authDomain: 'flutter-test-217c8.firebaseapp.com',
    storageBucket: 'flutter-test-217c8.firebasestorage.app',
  );
}
